## imort library

In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import os

In [7]:
PROJ_DIR=r"/home/sunbeam/Documents/flight_price"
DATA_DIR="data"

In [8]:
def get_data(name):
    file_name=f"{name}.csv"
    file_path=os.path.join(PROJ_DIR,DATA_DIR,file_name)
    return pd.read_csv(file_path)

SyntaxError: unterminated string literal (detected at line 1) (3698387336.py, line 1)

In [11]:
flights=get_data("flight_price")

In [12]:
flights

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [13]:
flights.sample(50
              )

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
2893,SpiceJet,24/05/2019,Kolkata,Banglore,CCU → BLR,22:20,00:40 25 May,2h 20m,non-stop,No check-in baggage included,3841
6012,Jet Airways,12/05/2019,Kolkata,Banglore,CCU → BOM → BLR,21:10,10:05 13 May,12h 55m,1 stop,In-flight meal not included,8586
180,Jet Airways,1/06/2019,Delhi,Cochin,DEL → BOM → COK,10:00,04:25 02 Jun,18h 25m,1 stop,In-flight meal not included,10262
4066,SpiceJet,21/03/2019,Mumbai,Hyderabad,BOM → HYD,22:45,00:10 22 Mar,1h 25m,non-stop,No info,1759
4911,IndiGo,09/03/2019,Banglore,New Delhi,BLR → HYD → DEL,16:55,21:50,4h 55m,1 stop,No info,4259
7355,Vistara,9/06/2019,Banglore,Delhi,BLR → DEL,11:30,14:20,2h 50m,non-stop,No info,4668
7786,IndiGo,15/06/2019,Chennai,Kolkata,MAA → CCU,14:45,17:05,2h 20m,non-stop,No info,3597
3229,Jet Airways,21/05/2019,Kolkata,Banglore,CCU → BOM → BLR,21:10,22:35 22 May,25h 25m,1 stop,In-flight meal not included,10844
10455,IndiGo,1/06/2019,Delhi,Cochin,DEL → COK,14:25,17:40,3h 15m,non-stop,No info,6015
1147,IndiGo,24/06/2019,Kolkata,Banglore,CCU → BLR,21:25,00:05 25 Jun,2h 40m,non-stop,No info,4804
4771,Air India,3/03/2019,Delhi,Cochin,DEL → BOM → COK,19:00,07:40 04 Mar,12h 40m,1 stop,No info,14777
8209,Multiple carriers,24/05/2019,Delhi,Cochin,DEL → BOM → COK,13:00,21:00,8h,1 stop,No info,14067
684,IndiGo,27/05/2019,Banglore,Delhi,BLR → DEL,21:15,00:15 28 May,3h,non-stop,No info,3943
2822,Air India,24/05/2019,Kolkata,Banglore,CCU → DEL → COK → TRV → BLR,10:00,10:30 25 May,24h 30m,3 stops,No info,13007
7775,Multiple carriers,18/05/2019,Delhi,Cochin,DEL → BOM → COK,06:00,12:35,6h 35m,1 stop,No info,9794
8495,IndiGo,27/04/2019,Banglore,Delhi,BLR → DEL,18:25,21:20,2h 55m,non-stop,No info,4823
4834,Air India,6/04/2019,Banglore,Delhi,BLR → DEL,06:10,08:55,2h 45m,non-stop,No info,5176
3032,Jet Airways,01/03/2019,Banglore,New Delhi,BLR → BDQ → DEL,05:50,12:20,6h 30m,1 stop,Business class,28097
2947,Multiple carriers,3/06/2019,Delhi,Cochin,DEL → BOM → COK,11:30,19:15,7h 45m,1 stop,No info,14848
244,Vistara,18/03/2019,Chennai,Kolkata,MAA → CCU,07:05,09:20,2h 15m,non-stop,No info,4842
425,Jet Airways,6/06/2019,Delhi,Cochin,DEL → BOM → COK,09:00,19:00,10h,1 stop,No info,14714
2155,Multiple carriers,27/06/2019,Delhi,Cochin,DEL → BOM → COK,18:00,01:30 28 Jun,7h 30m,1 stop,No info,7198
1141,Jet Airways,27/03/2019,Delhi,Cochin,DEL → BOM → COK,19:45,19:45 28 Mar,24h,1 stop,In-flight meal not included,5963
7795,Jet Airways,9/05/2019,Delhi,Cochin,DEL → JAI → BOM → COK,09:40,19:00,9h 20m,2 stops,In-flight meal not included,13029
7857,Multiple carriers,27/03/2019,Delhi,Cochin,DEL → BOM → COK,13:00,21:00,8h,1 stop,No info,6883
9830,IndiGo,15/04/2019,Delhi,Cochin,DEL → HYD → COK,07:35,16:10,8h 35m,1 stop,No info,6442
3181,IndiGo,1/05/2019,Banglore,Delhi,BLR → DEL,13:00,15:50,2h 50m,non-stop,No info,4423
7058,Air Asia,9/04/2019,Banglore,Delhi,BLR → DEL,23:55,02:45 10 Apr,2h 50m,non-stop,No info,4483
5946,IndiGo,6/06/2019,Mumbai,Hyderabad,BOM → HYD,19:05,20:35,1h 30m,non-stop,No info,2754
3205,IndiGo,24/06/2019,Mumbai,Hyderabad,BOM → HYD,19:05,20:35,1h 30m,non-stop,No info,2754
6938,Air Asia,12/06/2019,Kolkata,Banglore,CCU → DEL → BLR,07:35,19:25,11h 50m,1 stop,No info,5192
5336,Jet Airways,24/06/2019,Delhi,Cochin,DEL → NAG → BOM → COK,06:45,04:25 25 Jun,21h 40m,2 stops,No info,13376
5490,Multiple carriers,18/05/2019,Delhi,Cochin,DEL → BOM → COK,13:00,01:30 19 May,12h 30m,1 stop,No info,9385
7600,Jet Airways,12/05/2019,Kolkata,Banglore,CCU → BOM → BLR,21:10,08:15 13 May,11h 5m,1 stop,In-flight meal not included,8586
8891,Jet Airways,1/05/2019,Kolkata,Banglore,CCU → BOM → BLR,16:30,04:40 02 May,12h 10m,1 stop,In-flight meal not included,8586
3410,Jet Airways,1/05/2019,Kolkata,Banglore,CCU → DEL → BLR,20:25,10:55 02 May,14h 30m,1 stop,No info,12121
7587,Jet Airways,6/03/2019,Delhi,Cochin,DEL → BOM → COK,09:55,18:50,8h 55m,1 stop,In-flight meal not included,15400
8396,Jet Airways,24/06/2019,Delhi,Cochin,DEL → ATQ → BOM → COK,18:20,04:25 25 Jun,10h 5m,2 stops,No info,13775
2497,Air India,01/03/2019,Banglore,New Delhi,BLR → VGA → DEL,10:30,22:55,12h 25m,1 stop,No info,11003
8611,IndiGo,01/03/2019,Banglore,New Delhi,BLR → HYD → DEL,07:30,12:20,4h 50m,1 stop,No info,8110
8686,IndiGo,9/06/2019,Chennai,Kolkata,MAA → CCU,07:55,10:15,2h 20m,non-stop,No info,3850
5560,Air India,24/06/2019,Delhi,Cochin,DEL → MAA → COK,20:40,09:25 25 Jun,12h 45m,1 stop,No info,7480
1646,Jet Airways,06/03/2019,Banglore,New Delhi,BLR → BOM → DEL,05:45,05:05 07 Mar,23h 20m,1 stop,No info,13555
7695,IndiGo,9/06/2019,Delhi,Cochin,DEL → BOM → COK,06:40,21:00,14h 20m,1 stop,No info,6093
255,SpiceJet,21/03/2019,Mumbai,Hyderabad,BOM → HYD,13:10,14:30,1h 20m,non-stop,No info,3173
5089,IndiGo,12/06/2019,Delhi,Cochin,DEL → BOM → COK,20:25,01:30 13 Jun,5h 5m,1 stop,No info,5058
8000,Jet Airways,18/03/2019,Banglore,New Delhi,BLR → BOM → DEL,11:40,10:25 16 Mar,22h 45m,1 stop,In-flight meal not included,11087
7150,Multiple carriers,27/06/2019,Delhi,Cochin,DEL → HYD → COK,07:10,22:30,15h 20m,1 stop,In-flight meal not included,6093
3716,IndiGo,3/06/2019,Chennai,Kolkata,MAA → CCU,07:55,10:15,2h 20m,non-stop,No info,3850
2887,Multiple carriers,18/05/2019,Delhi,Cochin,DEL → BOM → COK,08:45,21:00,12h 15m,1 stop,No info,7670

In [14]:
flights.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

-  The data set contains 10,683 rows and 11 features
-   column "route and total stop " have missing values
-   The data type of some features are not appropriate

### Prelimnary Analysis

#### 1]check data Type

In [31]:
flights.dtypes

Airline            object
Date_of_Journey    object
Source             object
Destination        object
Route              object
Dep_Time           object
Arrival_Time       object
Duration           object
Total_Stops        object
Additional_Info    object
Price               int64
dtype: object

In [33]:
value=flights.Dep_Time.iloc[6]
value

'18:55'

In [25]:
flights.head()`

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

#### 2]Check For Duplicates

In [35]:
flights.duplicated().sum()

220

In [38]:
(
    flights.loc[flights.duplicated(keep=False)].sort_values(["Airline","Date_of_Journey","Source","Destination"])
)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
6321,Air India,01/03/2019,Banglore,New Delhi,BLR → BOM → AMD → DEL,08:50,23:55 02 Mar,39h 5m,2 stops,No info,17135
9848,Air India,01/03/2019,Banglore,New Delhi,BLR → BOM → AMD → DEL,08:50,23:55 02 Mar,39h 5m,2 stops,No info,17135
572,Air India,03/03/2019,Banglore,New Delhi,BLR → DEL,21:10,23:55,2h 45m,non-stop,No info,7591
8168,Air India,03/03/2019,Banglore,New Delhi,BLR → DEL,21:10,23:55,2h 45m,non-stop,No info,7591
1495,Air India,1/04/2019,Kolkata,Banglore,CCU → DEL → COK → BLR,10:00,01:20 02 Apr,15h 20m,2 stops,No info,10408
...,...,...,...,...,...,...,...,...,...,...,...
2692,SpiceJet,24/03/2019,Banglore,New Delhi,BLR → DEL,05:45,08:35,2h 50m,non-stop,No check-in baggage included,4273
2870,SpiceJet,24/03/2019,Banglore,New Delhi,BLR → DEL,05:45,08:35,2h 50m,non-stop,No check-in baggage included,4273
3711,SpiceJet,24/03/2019,Banglore,New Delhi,BLR → DEL,20:30,23:20,2h 50m,non-stop,No check-in baggage included,3873
2634,Vistara,24/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,5403
5470,Vistara,24/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,5403

#### oberavations from premlinary Analyis

 -
  The data type of "Date of journy" ,"Dep_time "and "Arival_time" should be  change to Dtaetime
 - The type of "Duration" and "Stops " is mixed .its should be numeric type
 - There are 220  duplicates .These Should be Removed

## 4 Detail Analysis

In [67]:
flights.select_dtypes(include="O").columns

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info'],
      dtype='object')

-
  i want to remove the extra spaces from strip  how will i will i do

-  flights["airline"]=flights["airline"].str.strip()
-  its overriding  the current dateframe
-  df_ will hold the cureent state of the object

## 5 Cleaning Operations

In [72]:
def clean_data(df):
    return (df
            .assign(**{
                col:df[col].str.strip()
                for col in df.select_dtypes(include="O").columns
                
            }
                
            )
            .rename(columns=str.lower)
          
           )

In [73]:
clean_data(flights)

,airline,date_of_journey,source,destination,route,dep_time,arrival_time,duration,total_stops,additional_info,price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

## 6 Split The Data